# Generated by Django 4.0.6 on 2022-07-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qr_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qr_Name', models.CharField(max_length=200, verbose_name='Name')),
                ('Qr_Code', models.ImageField(blank=True, upload_to=None, verbose_name='Code')),
            ],
        ),
    ]
