# Generated by Django 4.0.6 on 2022-07-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_gen', '0002_qr_code_delete_qr_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qr_code',
            name='Qr_Code',
            field=models.ImageField(blank=True, upload_to='qrMedia', verbose_name='Code'),
        ),
    ]
