# Generated by Django 4.0.6 on 2022-07-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_gen', '0003_alter_qr_code_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qr_code',
            old_name='Qr_Code',
            new_name='Qr_Image',
        ),
    ]
